# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: "pipeline.Replace"
    rules: "data/replace.json"
    force: false  # false if you want to use the rules used in the training process, otherwise, it always forces to load the file. The true is used to in developing testing to avoid retraining each time you change the rules. The true value will not work in production. By default false.
  - name: "SpacyNLP" # Initializes spacy structures. Every spacy component relies on this, hence this should be put at the beginning of every pipeline that uses any spacy components.
    model: "en"
    case_sensitive: false
  - name: SpacyTokenizer
    intent_tokenization_flag: False  # Flag to check whether to split intents
    intent_split_symbol: "+"  # Symbol on which intent should be split
  - name: RegexFeaturizer
  - name: SpacyFeaturizer
    ner_feature_vectors: True  # Whether to add word vectors to ``ner_features`` (default: False)
  - name: LexicalSyntacticFeaturizer
    "features": [
      [ "low", "title", "upper" ],
      [ "BOS", "EOS", "low", "upper", "title", "digit", "pos" ],
      [ "low", "title", "upper" ],
    ]
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer  # For BERT use LexicalSyntacticFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1
  - name: "pipeline.PublishSpacyTokens"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
